### PR TITLE
[ISSUE #216] pagination can chose pageSize

### PR DESCRIPTION
**Pull request by 847850277**
Hi, community
I have finished pagination can chose pageSize other module,include plugin and sysconfig.
see Issues [#216 ](https://github.com/apache/incubator-shenyu-dashboard/issues/216)
please review code.

### CODE REVIEW

**Comment by yu199195** [comment]
can you show result image？

**Comment by 847850277** [comment]
like this. I think it can play a role when there are many result data

image


image

**Review by yu199195 — APPROVED** [review]

**Comment by yu199195** [comment]
Hi， mybe show more page number ,like this <1,2,3,4,5,6...>

**Comment by 847850277** [comment]
I'll take time to adjust it later

**Pull request merged**
