### PR TITLE
fix plugin : change field of role maxLength from 10 to 50

### PR DESCRIPTION
**Pull request by Switch-vov**

### CODE REVIEW

**Comment by Switch-vov** [comment]
I think the length of role should more than 10 character
image

**Comment by Switch-vov** [comment]
@yu199195 After merge,  should I update the submodule `shenyu-dashboard` in `incubator-shenyu` ?

**Comment by dengliming** [comment]
> @yu199195 After merge, should I update the submodule `shenyu-dashboard` in `incubator-shenyu` ?

@Switch-vov Yes.

**Comment by Switch-vov** [comment]
> > @yu199195 After merge, should I update the submodule `shenyu-dashboard` in `incubator-shenyu` ?
> 
> @Switch-vov Yes.

Ok.

**Review by dengliming — APPROVED** [review]

**Pull request merged**
